apiVersion: v1
kind: Pod
metadata:
  name: pangolin-monitor-test
  labels:
    app: pangolin-monitor
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: curl
      image: curlimages/curl:8.0
      command: ["curl"]
      args: ["-f", "http://pangolin-monitor:8080/healthz"]
  restartPolicy: Never
